# Generated by Django 3.2.4 on 2021-06-24 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=225, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Description', max_length=225, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='SKU', max_length=225, verbose_name='SKU')),
                ('name', models.CharField(help_text='Name', max_length=225, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Description', max_length=225, null=True, verbose_name='Description')),
                ('pvp', models.DecimalField(decimal_places=2, help_text='Price of sale', max_digits=9, verbose_name='PVP')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='catalogue.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=None, upload_to='product', verbose_name='Images')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='catalogue.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product detail',
                'verbose_name_plural': 'Product details',
                'ordering': ('id', 'product'),
            },
        ),
    ]
