# Generated by Django 3.2.4 on 2021-06-24
from decimal import Decimal

from django.db import migrations


def load_product(apps, schema_editor):
    Product = apps.get_model('catalogue', 'Product')

    Product(sku=123456,
            name='Polo',
            description=None,
            pvp=Decimal(15),
            category_id=1
            ).save()
    Product(sku=128266,
            name='Short',
            description=None,
            pvp=Decimal(35),
            category_id=1
            ).save()
    Product(sku=12345326,
            name='Camisa',
            description=None,
            pvp=Decimal(30),
            category_id=1
            ).save()
    Product(sku=1442336,
            name='Terno',
            description=None,
            pvp=Decimal(250),
            category_id=1
            ).save()
    Product(sku=5435256,
            name='Gorro',
            description=None,
            pvp=Decimal(15),
            category_id=1
            ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_product)
    ]
